# Instance name that will be shown in with placeholders
Name: '%NAME%'

# This number will be used to sort the GUI slots
Sorting: %SORTING%

# The luckperms permission track which connects to this rank batch.
# If you do not want to use permission rewards for ranks, Leave this empty.
Track: '%TRACK%'

# The item to be showed in batch menu
Icon:
  Material: DIAMOND_SOWRD
  Name: 'ยง6%NAME%'

# Required permission to allow players access this batch!
Permission: ''

# Number of times players can prestige. 0 means no prestige is allowed
# Prestige will reset their rank to first rank.
PrestigeLimit: 0

# The multiplier for "ALL" requirements of the ranks and it will stack every prestige
PrestigeMultiplier: 10

# Common commands for this batch, These commands will always be executed for each rank up
Commands:
  - 'broadcast %player_name% has ranked up to %agmranks_%INSTANCE%_rank_name%'