# Instance name that will be shown in with placeholders
Name: '%NAME%'

# This number will be used to sort the GUI slots
Sorting: 0

# The item to be showed in batch menu
Icon:
  Material: DIAMOND_SWORD
  Name: '&6%NAME%'

# Required permission to allow players access this batch!
Permission: ''

# Number of times players can prestige. 0 means no prestige is allowed
# Prestige will reset their rank to first rank.
PrestigeLimit: 0

# The multiplier for "ALL" requirements of the ranks and it will stack every prestige
PrestigeMultiplier: 10

# Common commands for this batch, These commands will be executed after player prestiges
Commands:
  - 'broadcast %player_name% has prestiged on %NAME%'